import { NextRequest, NextResponse } from "next/server";
import { client } from "@/sanity/lib/client";

export const revalidate = 86400; // 24 hours ISR

function blocksToMarkdown(blocks: any[]): string {
  if (!blocks || !Array.isArray(blocks)) return "";

  return blocks
    .map((block) => {
      if (block._type === "block") {
        const text = (block.children || [])
          .map((child: any) => {
            let str = child.text || "";
            if (child.marks && Array.isArray(child.marks)) {
              if (child.marks.includes("strong")) str = `**${str}**`;
              if (child.marks.includes("em")) str = `*${str}*`;
              if (child.marks.includes("code")) str = `\`${str}\``;
            }
            return str;
          })
          .join("");

        const style = block.style || "normal";
        if (style === "h1") return `# ${text}\n`;
        if (style === "h2") return `\n## ${text}\n`;
        if (style === "h3") return `\n### ${text}\n`;
        if (style === "h4") return `\n#### ${text}\n`;
        if (style === "blockquote") return `\n> ${text}\n`;
        if (block.listItem === "bullet") return `- ${text}`;
        if (block.listItem === "number") return `1. ${text}`;

        return `${text}\n`;
      }

      if (block._type === "code") {
        const lang = block.language || "";
        const filename = block.filename ? `# ${block.filename}\n` : "";
        return `\n\`\`\`${lang}\n${filename}${block.code || ""}\n\`\`\`\n`;
      }

      if (block._type === "image") {
        return `\n![${block.alt || "Article illustration"}](Image)\n`;
      }

      return "";
    })
    .join("\n");
}

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ slug: string }> }
) {
  const { slug } = await context.params;

  const query = `*[_type == "post" && slug.current == "${slug}"]{
    title,
    summary,
    content,
    _createdAt,
    faqs,
    author->{name},
    categories[]->{title}
  }[0]`;

  const post = await client.fetch(query);

  if (!post) {
    return new Response("# 404: Article Not Found\n\nThe requested article could not be found.", {
      status: 404,
      headers: { "Content-Type": "text/markdown; charset=utf-8" },
    });
  }

  const categoryList = (post.categories || []).map((c: any) => c.title).join(", ");
  const dateFormatted = post._createdAt
    ? new Date(post._createdAt).toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
      })
    : "";

  let md = `# ${post.title}\n\n`;
  md += `> **Author:** ${post.author?.name || "Owais Abdullah"}  \n`;
  md += `> **Published:** ${dateFormatted}  \n`;
  if (categoryList) md += `> **Categories:** ${categoryList}  \n`;
  md += `> **Canonical URL:** https://owaisabdullah.dev/blog/${slug}  \n\n`;

  if (post.summary) {
    md += `## Overview\n\n${post.summary}\n\n`;
  }

  md += `## Content\n\n${blocksToMarkdown(post.content)}\n\n`;

  if (post.faqs && Array.isArray(post.faqs) && post.faqs.length > 0) {
    md += `## Frequently Asked Questions\n\n`;
    post.faqs.forEach((faq: any) => {
      md += `### ${faq.question}\n\n${faq.answer}\n\n`;
    });
  }

  md += `---\n*Generated by Owais Abdullah Portfolio Agent Indexer (https://owaisabdullah.dev)*\n`;

  return new Response(md, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
}
